### ISSUE TITLE
How can i run your project?

### ISSUE THREAD

**Issue by wyandun** [rickypeng99/yugioh_web#7]
Hi, im really fascinate with your job, but i cant run to play it, can you help me?

**Comment by rickypeng99** [comment]
Hi, and thank you!

To run the project, you will have to first clone [yugioh_web_server](https://github.com/rickypeng99/yugioh_web_server). Then `cd` into the folder and run `node index.js`. After that, clone this repo and open up two new terminals (so you can simulate two players playing against each other) and then run `npm start` for each of them. Feel free to reach out if there is any other problem.
